# Generated by Django 5.1.2 on 2024-11-09 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='竞赛名称')),
                ('type_labels', models.CharField(max_length=255, verbose_name='类型')),
                ('level_labels', models.CharField(max_length=255, verbose_name='级别')),
                ('description', models.TextField(verbose_name='简介')),
                ('website', models.URLField(verbose_name='竞赛官网')),
                ('other_info', models.TextField(blank=True, null=True, verbose_name='其他信息')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('date', models.DateField(verbose_name='日期')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='competition.competition')),
            ],
        ),
    ]
