# Generated by Django 5.1.2 on 2024-11-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='level_labels',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='type_labels',
        ),
        migrations.AddField(
            model_name='competition',
            name='levels',
            field=models.JSONField(default=list, verbose_name='竞赛级别'),
        ),
        migrations.AddField(
            model_name='competition',
            name='types',
            field=models.JSONField(default=list, verbose_name='竞赛类型'),
        ),
    ]
